### ISSUE TITLE
Failure if cache for remote FS is not configured

### ISSUE THREAD

**Issue by mschnepf** [riga/law#105]
If no cache is configured for wlcg_fs in law.cfg, law crashed with

`UnboundLocalError: local variable 'lpath' referenced before assignment`

https://github.com/riga/law/blob/1c846e171bad0d3c76dd990d4b260d2e91eae57e/law/target/remote.py#L1098-L1111

**Comment by riga** [comment]
Hi @mschnepf ,

sorry, this issue slipped through completely, but thanks for reporting!
