### ISSUE TITLE
Enable copying of directories (directory targets)

### ISSUE THREAD

**Issue by Nollde** [riga/law#109]
The target module implements the copying of files (file targets) [1].
It would be nice to also enable the copying of whole directories (directory targets).
A possible implementation of a file-directory-capable copying function could look like this [2]:

```
import shutil, errno

def copyanything(src, dst):
    try:
        shutil.copytree(src, dst)
    except OSError as exc: # python >2.5
        if exc.errno == errno.ENOTDIR:
            shutil.copy(src, dst)
        else: raise

```

[1]: https://github.com/riga/law/blob/master/law/target/local.py#L221-L233
[2]: https://stackoverflow.com/questions/1994488/copy-file-or-directories-recursively-in-python

**Comment by riga** [comment]
Hi @Nollde ,
thanks for opening. Yes, this has been on my list for quite a while. The local implementation is straight forward, unlike the remote one which requires some time. However, it should actually be possible with the updated remote file interface.

**Comment by riga** [comment]
Added in 44e0f0ea93e8226b1457d28305b70723a7e85b76.
