### ISSUE TITLE
Question on flow package on PyPI

### ISSUE THREAD

**Issue by Schamper** [riga/law#115]
Apologies for the misuse of issues on this project, but I've been trying to reach you with regards to another package you have on PyPI, `flow`.

I've been attempting to contact you via email to ask if you would be open to transferring the `flow` package name. Would you be able to get back to me on that?

Thanks!

**Comment by riga** [comment]
We will use the package soon for a public project.

**Comment by Schamper** [comment]
Hi @riga, it's been a few years and it looks like you're no longer the `flow` package name in favor of `columnflow`. We'd still be very appreciative if you'd allow us to use `flow`!
