### ISSUE TITLE
New project using law: SUSY Searches at DESY

### ISSUE THREAD

**Issue by frengelk** [riga/law#129]
## Project details

- a link to your repository: https://github.com/frengelk/Susy1LeptonAnalysis
- a link to a documentation if you have one: https://github.com/frengelk/Susy1LeptonAnalysis/wiki

## Project details

Analysis framework for CMS SUSY searches going from custom NanoAODs -> NTuple production -> DNN-based inference -> final plots and fits

**Comment by riga** [comment]
Added in #130.
