### ISSUE TITLE
Don't print "...and 1 more" when remote jobs fail

### ISSUE THREAD

**Issue by lmoureaux** [riga/law#136]
In a variety of situations, Law prints the status of the first few job followed by `...and N more`. It adds the `...and N more` even when N is 1 and printing the extra job would have taken as much space as the `...and 1 more` line.

I think code like this could account for the extra line by checking `i + 2` instead of `i + 1`:
https://github.com/riga/law/blob/70a223f57512e9e3e377a27709ad74067dacf07f/law/workflow/remote.py#L832-L838

**Comment by riga** [comment]
I think this should be done together with #135, increasing the threshold by 1 as you proposed.

**Comment by lmoureaux** [comment]
Works great!
