### ISSUE TITLE
Can't use `pathlib`'s `Path` for targets

### ISSUE THREAD

**Issue by StFroese** [riga/law#167]
I was trying to use `pathtlib`'s `Path` for my targets since I like the simplicity of

```python
path = Path('foo')
subfolder = path / "bar"
```

This stops working when the output method is called, for instance:
```python
def output(self):
    self.local_target(f"mc_dataset_{self.task_id}")

def local_target(self, path, *args):
    """Path to the local target."""
    return LocalFileTarget(self.build_path() / path, *args)

```
This is the case because the `remove_scheme` method in the `get_path` method inside `LocalFileTarget` expects a string

https://github.com/riga/law/blob/ce82c5f566b853a7ec24881663669f8344445846/law/target/file.py#L505-L508

@riga Do you want this to be an option for the user to use pathlib for example or should the user fix this themself by converting to a str?

Quick fix would be something like this:
Before:
https://github.com/riga/law/blob/ce82c5f566b853a7ec24881663669f8344445846/law/target/file.py#L481-L486

After
```python
 def get_path(target): 
     if isinstance(target, FileSystemTarget): 
         path = getattr(target, "abspath", no_value) 
         if path != no_value: 
             return path
     if not isinstance(target, str):
         try:
             target = str(target)
         except:
             raise TypeError(f"Expected type `str` as target/path, got {type(target)}")
     return target 
```

**Comment by pfackeldey** [comment]
You have to convert is to a string, which is (reasonably) simple with a `pathlib.Path` object: https://git.rwth-aachen.de/3pia/cms_analyses/common/-/blob/master/tasks/base.py#L103-108

**Comment by StFroese** [comment]
Yes, converting it is not difficult at all :)

At some point one maybe also want to refactor the whole code to use `pathlib.Path` instead of `os` stuff. Would clean up the code maybe but not sure if it's worth it

**Comment by riga** [comment]
Thanks for opening this!

For the internal path handling it might be better to keep normal strings (some paths are passed down to luigi, some paths to the gfal2 bindings for remote target access), but I think the law target API should 100% support `Path`'s being passed to all methods.

**Comment by StFroese** [comment]
@riga thx :)
