### ISSUE TITLE
Make `job_file_dir` a parameter of `HTCondorWorkflow`

### ISSUE THREAD

**Issue by EthanMarx** [riga/law#180]
## Description
Currently,  the `job_file_dir` is set from the `law` config. I have a use case where multiple `HTCondorWorkflows` may be running simultaneously, in which case I noticed that job files were being overwritten by one another. 

The workaround I found was to hack in to the `htcondor_create_job_file_factory` hook:

```python
class MyHTCWorkflow(HTCondorWorkflow):

def htcondor_create_job_file_factory(self, **kwargs):
        # set the job file dir to proper location
        kwargs["dir"] = self.job_file_dir
        return super().htcondor_create_job_file_factory(**kwargs) 
```

So that I can set the `job_file_dir` in a task dependent way. 

This solution works fine, but this seems like a common enough use case that it should be more obvious how / where this can be set. I propose making this a parameter of the HTCondorWorkflow that can default to reading from the config if left unset. 

Can put together a PR if this is something that is desirable.

**Comment by riga** [comment]
Hi @EthanMarx ,

thanks for opening the issue!

How do your job file directories look like? Usually, there is a temporary directory that is created per job submission inside that `job_file_dir`. It's controlled by the `job:: job_file_dir_mkdtemp` setting which should default to `True` (see https://law.readthedocs.io/en/latest/config.html#job). Is that the case for you?

**Comment by EthanMarx** [comment]
Ah! I've been setting that to `False`, but only b/c I was misunderstanding what it does. Thanks for pointing that out - should resolve my issue!

**Comment by EthanMarx** [comment]
Can I ask about the naming convention for the sub directoriea?

**Comment by riga** [comment]
> Can I ask about the naming convention for the sub directories?

It's using the default of [`tempfile.mkdtemp`](https://github.com/riga/law/blob/master/law/job/base.py#L789).

**Comment by EthanMarx** [comment]
Thanks. Would it make sense to name these directories based off something like the task name?

**Comment by riga** [comment]
Yes, that would be good! I will change the option to also accept strings that will support a couple template variables like `tmp_XXXX_{task_id}`.

- More than two X's will be replace by random characters (just like the [standard mkdtemp](https://man7.org/linux/man-pages/man3/mkdtemp.3.html))
- `{task_id}` -> `task.live_task_id`
- `{task_family}` -> `task.task_family`

I should have time to work on this tomorrow.
