### ISSUE TITLE
`master` HTCondor workflow breaks submission of seemingly random jobs

### ISSUE THREAD

**Issue by HerrHorizontal** [riga/law#183]
## Bug description
With the latest commit on the master branch the HTCondorWorkflow execution breaks for random jobs with an output like:
```
running htcondor_wrapper_2701241706.sh for job number 211
empty htcondor job arguments for LAW_HTCONDOR_JOB_NUMBER 211
```
I noticed that the reported `LAW_HTCONDOR_JOB_NUMBER 211` does not correspond to the job number I would expect from the `Error`, `Log`, `Output`, and `stdall` files, that share for this particular job above the suffix `_863To864.txt`. This might be related.

**Comment by HerrHorizontal** [comment]
Checking out an earlier commit that doesn't include the HTCondor group submission introduced in PR #176, e.g. commit 1848c573f7b05e45299f749cf5f8da175026d416 seems to run fine. I expect the bug has been introduced in PR #176 .

**Comment by riga** [comment]
Hi @HerrHorizontal ,

odd indeed. Are you sure your workflow didn't pick up a submission json file that was generated with the previous submission mode?

Btw, for the time being, you can also set `job::htcondor_job_grouping_submit` to False without the need to switch to an older version.

**Comment by HerrHorizontal** [comment]
I have removed the submission json before I ran the test. So I am pretty sure that it didn't.

I will try this out. Where do I set the `job::htcondor_job_grouping_submit` configuration for a certain workflow?

**Comment by riga** [comment]
You can set this value globally in the config, or you put this into your htcondor workflow

```python
def htcondor_create_job_manager(self, **kwargs):
    job_manager = super().htcondor_create_job_manager(**kwargs)
    job_manager.job_grouping_submit = True
    job_manager.chunk_size_submit = 0  # all in one
    return job_manager
```

Regarding the issue you're seeing, I could not spot anything obviously wrong. Could you sent me the content of the submission directory, including the main job files? This would help. Thank you!

**Comment by harrypuuter** [comment]
Hi all,

i am currently observing the same issue as reported by @HerrHorizontal - when I look at the submission jdl and the arguments in the `htconodor_wrapper_xxxx.sh` file, the first submission looks fine. Problems arise, as soon as a single job fails, and jobs have to be resubmitted.

I have not looked into the implementation in more detail, but I would suspect something like 

- running jobs fail and will be resubmitted
- an updated arguments file for the resumission is created, that does not contain all jobs anymore, but only the ones to be resubmitted
- scheduled jobs, that have not started yet, are now able to start but since there is only a single arguments file (which was modified due to the resubmission) the error mentioned above can occur, resulting in a cascade of failing jobs.

Could this be the reason for the errors ?

**Comment by riga** [comment]
@harrypuuter 

Thanks for confirming and the suggestion! I think you're onto something. I'm going to create a reproducer this week to debug this further.

**Comment by HerrHorizontal** [comment]
I, and also independently @harrypuuter, have encountered another issue with the new HTCondor group submission. When turning the group submission off as suggested previously, with

> ```python
> def htcondor_create_job_manager(self, **kwargs):
>     job_manager = super().htcondor_create_job_manager(**kwargs)
>     job_manager.job_grouping_submit = True
>     job_manager.chunk_size_submit = 0  # all in one
>     return job_manager
> ```

the rendering of the values enclosed by double curly brackets, for instance `{{law_job_base}}`, in the job script fails. Also, it seems that the `'XToY'` suffix is not consistently attached to the files. This leads to the jobs failing already at the setup stage with File or Directory Not Found Errors.

**Comment by riga** [comment]
@HerrHorizontal @harrypuuter I think this should be fixed now, but could you give it a try as well?

Regarding the second issue you saw @HerrHorizontal , this might also be fixed now. However, if the issue persists, could you open a second ticket?

**Comment by riga** [comment]
@HerrHorizontal 

I just tried to replicate the issue and copied your exact job manager hook, but it's working on my end.

> ... for instance {{law_job_base}}, in the job script fails.

Can you elaborate what exactly fails here? Are the variables job replaced or is there in issue being raised?

Grouped condor jobs (submitting job *clusters*) can actually share input files, meaning that each job on the cluster uses the exact same file of the input sandbox and then handles variable rendering as part of the job (the variables for that are stored as per-job arguments). Therefore, when looking into files inside the submission directory on the login node, variables are not replaced. That being said, not all job input files *must* be shared. This can be decided per input file (see e.g. [here](https://github.com/riga/law/blob/master/law/contrib/htcondor/workflow.py#L267-L285); The `htcondor_group_wrapper_file` even has different settings than `htcondor_job_file`).

> Also, it seems that the 'XToY' suffix is not consistently attached to the files.

Do you declare each input file as a `JobInputFile` object? If so, which settings did you use? If sharing is enabled (which is the default for grouped submission), there is no `_XToY` suffix, but this will change as soon as you set `shared=False`.
