### ISSUE TITLE
Add spool option for HTCondor

### ISSUE THREAD

**Issue by TheRealLoliges486** [riga/law#186]
## Description

Hi, 

Currently as far as CERN is concerned, the submission of HTCondor jobs while on EOS is [not allowed. ](https://batchdocs.web.cern.ch/troubleshooting/eos.html#no-eos-submission-allowed) The usual workaround is using the `-spool` option while submitting (so basically `condor_submit -spool job.sub`). Consider implementing that to law.

Thanks :-)

**Comment by riga** [comment]
Added in e9408bfa.

The option defaults to `False`, but on task level you can define

```python
class MyTask(MyBaseTasks, HTCondorWorkflow):

    htcondor_job_kwargs_submit = {"spool": True}

    ....
```

to activate it.
