### ISSUE TITLE
LocalWorkflow not compatibe with WrapperTask

### ISSUE THREAD

**Issue by solo-driven** [riga/law#187]
## Bug description
 
...
When WrapperTask is used with LocalWorkflow only outputs existence is checked and not if the tasks are completed. When I remove localWorkflow everything works as expected 

```
import law


class taskB(law.Task):
    def run(self):
        ...

    def complete(self):
        return False
    

class taskA(law.Task):
    def run(self):
        ...

    def complete(self):
        return True
    

    
class Wrapper(law.WrapperTask, law.LocalWorkflow):
    def create_branch_map(self):
        return [1]
    
    def requires(self):
        return [taskA(),   taskB()]
```

will result in:
```
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 complete ones were encountered:
    - 1 Wrapper(...)

Did not run any tasks
This progress looks :) because there were no failed tasks or missing dependencies

===== Luigi Execution Summary =====
```

**Comment by riga** [comment]
Hi @solo-driven ,

this is not a bug but the behavior when you mix the two task classes that have separate definitions of what `complete()` means. A wrapper task is only meant to define requirements but it is not intended to do or run anything on its own (unlike workflows).

What is your use case why you mix the two in the first place?

**Comment by solo-driven** [comment]
I have a task which just yields other tasks and has no output. That's why I use `WrapperTask`.And final goal is to run simulation in HTCondor so I will use `HTCondorWorkflow`

**Comment by solo-driven** [comment]
https://github.com/solo-driven/cmssw-configurator/blob/main/configurator/law_task/param_combination.py


Here you can see what I am trying to do. Any advices will be appreciated :)

**Comment by riga** [comment]
> I have a task which just yields other tasks and has no output. 

You can achieve the same behavior by inheriting from `law.tasks.RunOnceTask`.

```python
import law
law.contrib.load("tasks")

class MyTask(law.LocalWorkflow, law.tasks.RunOnceTask):

    # implement the local_workflow_pre_run hook to mark the
    # task as complete once it ran
    def local_workflow_pre_run(self):
        self.mark_complete()

    ...  # your methods here
```

It also has it's own `complete()` implementation that does not interfere with workflows in the destructive way that `WrapperTask`'s do.
