### ISSUE TITLE
`MatplotlibFormatter` does not take (default) file permissions into account

### ISSUE THREAD

**Issue by cverstege** [riga/law#188]
## Bug description

When dumping a figure using the `MatplotlibFormatter`, default file permissions are ignored and can not be set via the kwargs.

Example:
`law.cfg`
```
[web_plots]
base = /web/cverstege/plots/
default_dir_perm = 0o0774
default_file_perm = 0o0664
```
`task.py`:
```py
import matplotlib.pyplot as plt
import law
from law.contrib.matplotlib import MatplotlibFormatter

class Plot(law.task):
    def output(self):
        return law.LocalFileTarget("plot.pdf", fs="web_plots")
    def run(self):
        fig, ax = plt.subplots()
        self.output().parent.touch()
        MatplotlibFormatter.dump(self.output(), fig)
```
The output file then has permission `644` instead of the expected `664`. The dir creation is fine.

Matplotlib itself does not suport setting file permissions: https://stackoverflow.com/questions/31669940/how-to-set-output-file-permissions-using-matplotlib-savefig
So this has to be worked around in the law `MatplotlibFormatter`.

**Comment by cverstege** [comment]
Easier way to test this:
```python
import matplotlib.pyplot as plt
import law
from law.contrib.matplotlib import MatplotlibFormatter

file_system = law.LocalFileSystem(base="/home/cverstege/src/law/tmp/plots", default_file_perm=0o0664)
plot_target = law.LocalFileTarget(path="1/plot.pdf", fs=file_system)

fig, ax = plt.subplots()
plot_target.makedirs()
MatplotlibFormatter.dump(plot_target, fig)

import os
from stat import ST_MODE
print(oct(os.stat("plots/1/plot.pdf")[ST_MODE]))

```

**Comment by riga** [comment]
Thanks for reporting @cverstege !
I will merge #191 now, but this got me thinking whether other formatters should implement something similar.

**Comment by cverstege** [comment]
> Thanks for reporting @cverstege ! I will merge #191 now, but this got me thinking whether other formatters should implement something similar.

That's for sure something to keep in mind. Other backends might support permissions directly unlike matplotlib. Then one would only need to set the correct kwarg.

**Comment by riga** [comment]
Fyi: Added in 976d53b.

**Comment by riga** [comment]
@cverstege Just a last comment: With the change in 976d53b, `chmod` is not invoked by default to not interfere with what libraries would normally set as permission flags. However, as soon as you set e.g. `perm=...`, the permissions are set. `None` leads to the default on that file system.

**Comment by cverstege** [comment]
Thanks for the in depth fix! Now it's easier when one has e.g. a shared data folder by using the group permissions Linux already provides :+1:
