### ISSUE TITLE
Show number of waiting jobs in status line.

### ISSUE THREAD

**Issue by riga** [riga/law#51]
While polling, remote workflows print status lines such as:

```
18:34:30: all:   44, pending:    4 (  +0), running:    0 (  +0), finished:    0 (  +0), retry:    0 (  +0), failed:    0 (  +0)
18:35:00: all:   44, pending:    2 (  -2), running:    2 (  +2), finished:    0 (  +0), retry:    0 (  +0), failed:    0 (  +0)
```

In the example above, the number of parallel running jobs is 4 (`--parallel-jobs 4`). However, this is not that obvious when looking at the status lines. Either the number of parallel jobs, or the number of currently waiting jobs should be added.

**Comment by erikgeiser** [comment]
Currently one of my jobs has the following status:
```
11:38:08: all:  256, pending:    0 (  +0), running:    0 (  +0), finished:  233 (  +0), retry:    0 (  +0), failed:    0 (  +0)
```
It seems like the job has somehow lost track of htcondor submissions. A `waiting` indicator would make the current status way more clear.
