### ISSUE TITLE
WLCG Targets absent when VOMS proxy is not valid

### ISSUE THREAD

**Issue by DavidS3141** [riga/law#60]
When the VOMS proxy is not valid anymore after a week, then WLCGFiles are displayed as absent using the `--print-status` functionality. This is misleading, better would be an error message or a different status than absent (e.g. unreachable).

**Comment by riga** [comment]
Yeah, that's actually right. But there are many different proxies to check for (`voms-proxy-init`, `arc-proxy`, ...). We should think of a way to display this before the actual status is printed.

**Comment by riga** [comment]
```python
import law
law.contrib.load("wlcg")

law.check_voms_proxy_validity(log=True)
```
