### ISSUE TITLE
Repository bundling with local changes in submodules does not work properly

### ISSUE THREAD

**Issue by pfackeldey** [riga/law#72]
Hi Marcel,

if you have submodules in your repository, the [bundle_repository](https://github.com/riga/law/blob/master/law/contrib/git/scripts/bundle_repository.sh) script does not add and commit local changes in submodules. Therefore local changes in submodules will not be bundled and not uploaded to a e.g. grid node. This makes fast debugging a bit inconvenient, since the user has to commit changes each time in each submodule by hand before bundling the repository.

Thank you already in advance for checking on this :)

**Comment by riga** [comment]
Hey, thanks for reporting!

Can you checkout the https://github.com/riga/law/tree/fix/git_submodule_bundling branch and see if it works as expected?

**Comment by pfackeldey** [comment]
Unfortunately I got the following bug during bundling:
`Stopping at '<submodule_name>'; script returned non-zero status.`

**Comment by riga** [comment]
Can you try again?

**Comment by pfackeldey** [comment]
I get this error now:
```sh
INFO: [pid 2011978] Worker Worker(salt=412274527, workers=1, host=lx3a53.physik.rwth-aachen.de, username=fackeldey, pid=2011978) running   law.git.UploadRepo(exclude_files=, include_files=, custom_checksum=NO_STR, replicas=10, analysis_choice=bbww_dl, notify_slack=False, notify_telegram=False)
/.automount/home/home__home1/institut_3a/fackeldey/dihiggs/common: /.automount/home/home__home1/institut_3a/fackeldey/dihiggs/common: is a directory
ERROR: [pid 2011978] Worker Worker(salt=412274527, workers=1, host=lx3a53.physik.rwth-aachen.de, username=fackeldey, pid=2011978) failed    law.git.UploadRepo(exclude_files=, include_files=, custom_checksum=NO_STR, replicas=10, analysis_choice=bbww_dl, notify_slack=False, notify_telegram=False)
Traceback (most recent call last):
  File "/net/scratch_cms3a/dihiggs/software/fackeldey/lib/python2.7/site-packages/luigi/worker.py", line 205, in run
    new_deps = self._run_get_new_deps()
  File "/net/scratch_cms3a/dihiggs/software/fackeldey/lib/python2.7/site-packages/luigi/worker.py", line 142, in _run_get_new_deps
    task_gen = self.task.run()
  File "/.automount/home/home__home1/institut_3a/fackeldey/dihiggs/common/tasks/base.py", line 317, in run
    self.bundle(bundle)
  File "/net/scratch_cms3a/dihiggs/software/fackeldey/lib/python2.7/site-packages/law/contrib/git/__init__.py", line 75, in bundle
    raise Exception("repository bundling failed")
Exception: repository bundling failed
```

**Comment by riga** [comment]
Yeah, I use `git ls-files --recurse-submodules` internally which was introduced to git 3 years ago. But since this is apparently not **yet** supported by Centos7 (the default version is 1.8.3.1 which is > 6 years old) I have to use sth else for backwards compatibility 🤔.

I will let you know when you can test again.

**Comment by riga** [comment]
Ping.
