### ISSUE TITLE
Autocompletion bug in law cli with certain namespaces for "SubTasks"

### ISSUE THREAD

**Issue by pfackeldey** [riga/law#87]
Hi,

I recently changed my task namespace to something with an underscore, e.g.: 
```python
class TestTask(law.Task):
    task_namespace = "abit_buggy"
    param = luigi.Parameter()
    ...

class TestTaskWrapper(law.WrapperTask):
    def requires(self):
        return [TestTask.req(self, param=param) for param in params]
```

Now the autocompletion for law completes only the following:

```shell
law run TestTaskWrapper --abit_buggy.TestTask-param ...`
```

but this leads to unrecognized parameters, instead one has to do:

```shell
law run TestTaskWrapper --abit-buggy.TestTask-param ...`
```

which is currently unfortunately not supported by the law autocompletion.

What are your thoughts on this @riga ?

**Comment by riga** [comment]
I can reproduce this. Will go down that completion rabbit hole tomorrow hopefully ;)

**Comment by riga** [comment]
@pfackeldey Can you checkout the [fix_autocompletion](https://github.com/riga/law/tree/fix_autocompletion) branch and see if the issue persists?

**Comment by pfackeldey** [comment]
Unfortunately it does not work yet completely. 

Now the issue is the following:

How it has to be:
```shell
law run abit_buggy.TestTaskWrapper --abit-buggy.TestTask-param ...
```
What autocompletion currently does:
```shell
law run abit-buggy.TestTaskWrapper --abit-buggy.TestTask-param ...
```

So i think the point is that the "-" <-> "_" has to be only changed for the subtasks.

**Comment by riga** [comment]
@pfackeldey Can you give it another shot?

**Comment by pfackeldey** [comment]
It works! perfect!!! 🎉 🎉 🎉

**Comment by riga** [comment]
Finally -.-

**Comment by riga** [comment]
Finally -.-
